name: BGP For each PR
on:
  pull_request:
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    name: E2E tests
    strategy:
      fail-fast: true
    steps:
      - name: Ensure fs wont cause issues
        run: sudo sysctl fs.inotify.max_user_instances=8192 && sudo sysctl fs.inotify.max_user_watches=524288
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build image locally
        run: make dockerx86Local
      - name: Get GoBGP binaries
        run: make get-gobgp
      - name: Run BGP mode tests v1.29.0 onwards
        run: sudo -E PATH=$PATH DOCKER_API_VERSION=1.48 make e2e-tests129-bgp
