name: SERVICES For each PR
on:
  pull_request:
jobs:
  service-tests:
    runs-on: ubuntu-latest
    name: E2E service tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build image with iptables
        run: make dockerx86ActionIPTables
      - name: Run tests
        run: DOCKERTAG=action make service-tests